GRANT SELECT ON BRONZE_USER.CRM_CUST_INFO TO SILVER_USER;
GRANT SELECT ON BRONZE_USER.crm_prd_info TO SILVER_USER;
GRANT SELECT ON BRONZE_USER.crm_sales_details TO SILVER_USER;
GRANT SELECT ON BRONZE_USER.erp_cust_az12 TO SILVER_USER;
GRANT SELECT ON BRONZE_USER.erp_loc_a101 TO SILVER_USER;
GRANT SELECT ON BRONZE_USER.erp_px_cat_g1v2 TO SILVER_USER;


