SELECT COUNT(*)
FROM
    (SELECT 
        ci.CST_ID,
        ci.CST_KEY,
        ci.CST_FIRST_NAME,
        ci.CST_LAST_NAME,
        ci.CST_MARITAL_STATUS,
        ci.CST_GNDR,
        ca.GEN,
        ci.CST_CREATE_DATE,
        ca.BDATE,
        la.CNTRY

    FROM SILVER_USER.crm_cust_info ci
    LEFT JOIN SILVER_USER.ERP_CUST_AZ12 ca
    ON ci.CST_KEY = ca.CID
    LEFT JOIN SILVER_USER.ERP_LOC_A101 la
    ON ci.CST_KEY = la.CID)
    GROUP BY CST_KEY
    HAVING COUNT(*) > 1;

    -- THERE IS NO DUPLICATE ABOVE RECORDS.





SELECT 
    ci.CST_ID,
    ci.CST_KEY,
    ci.CST_FIRST_NAME,
    ci.CST_LAST_NAME,
    ci.CST_MARITAL_STATUS,
    CASE WHEN
        ci.CST_GNDR = 'n/a' THEN ca.GEN
        ELSE ci.CST_GNDR
    END AS GENDER,
    ci.CST_GNDR,
    ca.GEN,
    ci.CST_CREATE_DATE,
    ca.BDATE,
    la.CNTRY
    
FROM SILVER_USER.crm_cust_info ci
LEFT JOIN SILVER_USER.ERP_CUST_AZ12 ca
ON ci.CST_KEY = ca.CID
LEFT JOIN SILVER_USER.ERP_LOC_A101 la
ON ci.CST_KEY = la.CID
WHERE ci.CST_GNDR = 'n/a' AND ca.GEN != 'n/a';
-- NOW THE GENDER VALUE IS CORRECTED IN THE ABOVE RECORDS.




DESC SILVER_USER.ERP_CUST_AZ12;
DESC SILVER_USER.CRM_CUST_INFO;
DESC SILVER_USER.ERP_LOC_A101;

SELECT * 
FROM SILVER_USER.ERP_CUST_AZ12;

SELECT * 
FROM SILVER_USER.ERP_LOC_A101;




------------------------------------------------------------------------------------------------------------------------------------------------
-- TEST ON THE VIEW_02_GOLD_DIM_PRODUCTS
SELECT PRD_KEY, COUNT(*)
FROM
    (SELECT 
        PN.PRD_ID,
        PN.CAT_ID,
        PN.PRD_KEY,
        PN.PRD_NM,
        PN.PRD_COST,
        PN.PRD_LINE,
        PN.PRD_START_DT,
        PN.PRD_END_DT,
        PC.CAT,
        PC.SUBCAT,
        PC.MAINTENANCE

    FROM SILVER_USER.CRM_PRD_INFO PN
    LEFT JOIN SILVER_USER.ERP_PX_CAT_G1V2 PC
    ON PN.CAT_ID = PC.ID
    WHERE PRD_END_DT IS NULL)
    GROUP BY PRD_KEY
    HAVING COUNT(*) > 1;

    -- THERE IS NO DUPLICATE ABOVE RECORDS.

    ---------------------------------------------------------------------------------------------------------------------------
    -- TEST ON THE VIEW_03_GOLD_FACT_SALES

SELECT
    *
FROM SILVER_USER.CRM_SALES_DETAILS;

SELECT
    *
FROM GOLD_USER.GOLD_DIM_CUST;
SELECT 
    *
FROM GOLD_DIM_PRODUCTS;

SELECT 
    product_number,
    SUBSTR(product_number, 1, 7) AS PRODUCT_KEY1
FROM GOLD_DIM_PRODUCTS;


-------------------------------------------------------------------------------------------------------------------------------------------------
-- FOREIGN KEY INTERGRITY TESTS

SELECT
    *
FROM GOLD_USER.GOLD_FACT_SALES FS
LEFT JOIN GOLD_USER.GOLD_DIM_CUST DC
ON FS.CUSTOMER_KEY = DC.CUSTOMER_KEY
WHERE DC.CUSTOMER_KEY IS NULL;

-- SO ALL CUSTOMER_KEY IN FACT_SALES TABLE EXIST IN DIM_CUST TABLE.

-- NOW TESTING THE PRODUCT_KEY IN FACT_SALES TABLE.

SELECT
    *
FROM GOLD_USER.GOLD_FACT_SALES FS
LEFT JOIN GOLD_USER.GOLD_DIM_PRODUCTS DP
ON FS.PRODUCT_KEY = DP.PRODUCT_KEY
WHERE DP.PRODUCT_KEY IS NULL;
-- SO ALL PRODUCT_KEY IN FACT_SALES TABLE EXIST IN DIM_PRODUCTS TABLE.