CREATE OR REPLACE VIEW GOLD_USER.GOLD_CUST_DIM AS
SELECT
    ROW_NUMBER() OVER(ORDER BY ci.CST_ID) AS CUSTOMER_KEY,
    ci.CST_ID CUSTOMER_ID,
    ci.CST_KEY CUSTOMER_NUMBER,
    ci.CST_FIRST_NAME FIRST_NAME,
    ci.CST_LAST_NAME LAST_NAME,
    la.CNTRY COUNTRY,
    ci.CST_MARITAL_STATUS MARITAL_STATUS,
    CASE WHEN
        ci.CST_GNDR = 'n/a' THEN ca.GEN
        ELSE ci.CST_GNDR
    END AS GENDER,
    ca.BDATE BIRTHDAY,
    ci.CST_CREATE_DATE CREATE_DATE
    
FROM SILVER_USER.crm_cust_info ci
LEFT JOIN SILVER_USER.ERP_CUST_AZ12 ca
ON ci.CST_KEY = ca.CID
LEFT JOIN SILVER_USER.ERP_LOC_A101 la
ON ci.CST_KEY = la.CID;


SELECT *
FROM GOLD_USER.GOLD_CUST_DIM;