GRANT SELECT, INSERT, UPDATE, DELETE ON SILVER_USER.CRM_CUST_INFO TO GOLD_USER;
GRANT SELECT, INSERT, UPDATE, DELETE ON SILVER_USER.crm_prd_info TO GOLD_USER;
GRANT SELECT, INSERT, UPDATE, DELETE ON SILVER_USER.crm_sales_details TO GOLD_USER;
GRANT SELECT, INSERT, UPDATE, DELETE ON SILVER_USER.erp_cust_az12 TO GOLD_USER;
GRANT SELECT, INSERT, UPDATE, DELETE ON SILVER_USER.erp_loc_a101 TO GOLD_USER;
GRANT SELECT, INSERT, UPDATE, DELETE ON SILVER_USER.erp_px_cat_g1v2 TO GOLD_USER;