CREATE OR REPLACE VIEW GOLD_USER.GOLD_DIM_PRODUCTS AS
SELECT
    ROW_NUMBER() OVER(ORDER BY PN.PRD_START_DT, PN.PRD_KEY) AS PRODUCT_KEY,
    PN.PRD_ID AS Product_id,
    PN.PRD_KEY AS Product_number,
    PN.PRD_NM AS Product_name,
    PN.CAT_ID AS Category_id,
    PC.CAT AS Category,
    PC.SUBCAT AS Subcategory,
    PC.MAINTENANCE AS Maintenance,
    PN.PRD_COST  AS Cost,
    PN.PRD_LINE AS Product_line,
    PN.PRD_START_DT AS Product_start_date,
    PN.PRD_END_DT AS Product_end_date

FROM SILVER_USER.CRM_PRD_INFO PN
LEFT JOIN SILVER_USER.ERP_PX_CAT_G1V2 PC
ON PN.CAT_ID = PC.ID
WHERE PN.PRD_END_DT IS NULL;

SELECT
    *
FROM SILVER_USER.ERP_PX_CAT_G1V2;

SELECT
    *
FROM GOLD_USER.GOLD_DIM_PRODUCTS;