CREATE OR REPLACE VIEW GOLD_USER.GOLD_FACT_SALES AS
SELECT 
    SD.SLS_ORD_NUM AS ORDER_NUMBER,
    DP.PRODUCT_KEY,
    DC.CUSTOMER_KEY,
    SD.SLS_ORDER_DT AS ORDER_DATE,
    SD.SLS_SHIP_DT AS SHIP_DATE,
    SD.SLS_DUE_DT AS DUE_DATE,
    SD.SLS_SALES AS SALES_AMOUNT,
    SD.SLS_QUANTITY AS QUANTITY,
    SD.SLS_PRICE AS PRICE

    
FROM SILVER_USER.CRM_SALES_DETAILS SD
LEFT JOIN GOLD_USER.GOLD_DIM_CUST DC
ON SD.SLS_CUST_ID = DC.CUSTOMER_ID
LEFT JOIN GOLD_USER.GOLD_DIM_PRODUCTS DP
ON SD.SLS_PRD_KEY = SUBSTR(DP.product_number, 1, 7);


SELECT *
FROM GOLD_USER.GOLD_FACT_SALES;


